version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0-browsers
        environment:
          RAILS_ENV: test  
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run:
          name: Update Bundle
          command: bundle update
      - ruby/bundle-install
      #setup database
      - run: cp -v config/database.ci.yml
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      # Run rubocop  
      - run:  
          name: Run rubocop  
          command: bundle exec rubocop app/models app/controllers app/helpers
      # Run Rspec
      - run:
          name: Run rspec
          command: bundle exec rspec

  deploy:
    machine: true
    steps:
      - checkout
      - run: |-
          cat >> ~/.netrc \<<EOF
            machine api.heroku.com
              login haianh13041999@gmail.com
              password 2469ae51-f3fd-49ca-b760-9b8467658a07
            machine git.heroku.com
              login haianh13041999@gmail.com
              password 2469ae51-f3fd-49ca-b760-9b8467658a07
          EOF
      - run: chmod 600 ~/.netrc 
      - run: heroku git:remote -a pure-wildwood-68673
      - run: git push heroku master:master -f
      - run: heroku run rails db:migrate --app pure-wildwood-68673

workflows:
  version: 2.1
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
